### ISSUE TITLE
FEAT: Fire an event when a NEW node is found on the mesh.

### ISSUE THREAD

**Issue by asjmcguire** [broglep/homeassistant-meshtastic#21]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/broglep/homeassistant-meshtastic/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would quite like an event to be fired on the Home Assistant Event Bus when a new node is discovered on the mesh.

### Describe the solution you'd like

So the use case would something like this:
people drive through the village I live in, if there is a Met Office warning (UK) in force, upon a new node announcing itself to the mesh, I would then automatically send that node a direct message warning them about adverse weather.

It would be possible to use this in other ways though, imagine something like a treasure hunt, where as people arrive at each location, they are simply automatically sent the next clue as a direct message.

Or how about in my case for example I have the primary channel that I broadcast weather updates on less frequently, and a dedicated weather channel that I broadcast updates on much more frequently, BUT no-one knows about the sub channel with the more frequent updates. If however I could announce that the channel exists when a new node arrives on the mesh, then they could decide if they wanted to join that channel or not.

### Describe alternatives you've considered

There are no alternatives.

### Additional context

N/A

**Comment by broglep** [comment]
I like this idea / capability to react on new nodes, but there might be some details to be figured out (e.g. if we would want to wait for a neighbour info or not). I think we could look into the mobile apps how they behave and when they notify about a new node being discovered.

I did a little experiment and it is already possible via a small detour to the entity registry and make use of the notification platform (where notify entities are created when they appear)
```

alias: React to new Meshtastic Nodes
description: ""
triggers:
  - trigger: event
    event_type: entity_registry_updated
    event_data:
      action: create
conditions:
  - condition: template
    value_template: >-
      {{ trigger.event.data.entity_id is match('notify\.mesh_node_.*',
      ignorecase=False) }}
actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: >-
        New Node Discovered: {{ state_attr(trigger.event.data.entity_id,
        'friendly_name') }}
      title: Meshtastic
mode: single
```
Maybe you can start with that and try it out to get a better feeling if that already solves some of the usecases
