### ISSUE TITLE
Way to not create notify entities in Home Assistant when a new node is found

### ISSUE THREAD

**Issue by Ylianst** [broglep/homeassistant-meshtastic#22]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/broglep/homeassistant-meshtastic/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

This is a wonderful integration, I have been waiting for exactly this sort of integration to remove MQTT. I see over 100 nodes in my area. Is there any way to not create new entities when a new node is found? I am concerned this if flooding my HA with a not of entities with names I can't control (node_xxx). I am also next to a highway and a lot of nodes are visiting and not going to be seen again.

### Describe the solution you'd like

Have a configuration switch to not create nodes when discovered.

### Describe alternatives you've considered

Current MQTT is the alternative, but having a solution that uses the real Meshtastic API is much better.

### Additional context

Thank you so much! I have been looking for exactly this type of integration. An addition to this is to be able to reply to a node that sends a direct/channel message without having the node entity created.

**Comment by Ylianst** [comment]
Arg. Found the option. Thanks!

**Comment by Ylianst** [comment]
Actually the configuration is to not enable new nodes, but they are still created. I will check to see if they are removed after they timeout of not. If not removed, I could quickly accumulate 100's of node entities.

**Comment by broglep** [comment]
I assume you used `System options` -> `Enable newly added entities` right ?

Currently the integration creates notify entities for the full node database (and all new discovered nodes) and the rest of the entities (sensor, device tracker, etc) are only created for the nodes you select as part of the configuration / setup of the integration. 
I did already think about the option to make the notify platform configurable as I'm also not big fan of cluttering home assistant with many entities. I did also think about a service that allows to clear (or expire) the notify entities to address the ever growing nature of the current implementation (which for some might be desired if they want to retain the node database even in case the meshtastic nodes does forget it)

If you know the node id or channel index, you can send messages without the need for the entities, you can use `meshtastic.send_text` service/action in that case. You could use the `meshtastic_api_text_message` event to react on messages (on a channel or private message). But that would be rather an advanced use case

**Comment by Ylianst** [comment]
@broglep Thank you so much for your reply. You are exactly correct, I found `System options -> Enable newly added entities` but indeed, after 10 hours, I am already back to 180 entities and this will only go up. Since this option is enabled by default, I have to go manually disable all the entities between integration install and when I get this option disabled.

![{D2273892-4713-4EA2-9F87-607EA39E8ED2}](https://github.com/user-attachments/assets/1eee6f4e-32fa-4c00-a552-c1d03d07d855)

I did figure out that I can uninstall/reinstall the integration to clean up the entities, but in my situation, it's going to be a lot of clutter for sure. I do really like being able to create all of the sensors for nodes I select. I have one "mobile" Meshtastic node I want to track, but for all other nodes, I would like no entities at all.

By the way, this is great work. With auto-discovery, clean set of sensors, modern events, this is certainly on the path to what should be the official Meshtastic Home Assistant integration. It feels very professional. I completely disabled MQTT for this use case yesterday and not going back.

I am going to go try `meshtastic.send_text` with a nodeid right now.

**Comment by broglep** [comment]
I'm right now working on making the notification platform configurable so that you can select if you would like to create channel and/or node notify targets or not. I think that should also address your use case. There might be even a need for a third option to create notify targets only for selected nodes. That way you could still use the recommended notify platform way of sending messages to the few nodes that you are tracking 

I still struggle a bit with home assistant config flow & options, but once that is sorted out, it should be done quickly.

**Comment by Ylianst** [comment]
I have had to work my way up the Home Assistant learning curve myself for my own integration, so, I completely understand. I have used ChatGPT a bit to help out with mixed success.

With Meshtastic adding MQTT flags and control in the latest versions, using MQTT as a bridge to Home Assistant is not a great option anymore. You now have to turn on "allow MQTT" on the sender side to get a message to HA, it's not a good experience and MQTT integration to a bit of a hack. This is a very welcome integration for sure.

I am trying `meshtastic.send_text` and yes, this is exactly perfect. However, when I receive a message, I don't seem to have the senders Meshtastic NodeID. The 'device_id' is the node id of the device that received the message, but I don't have the source node id and so, can't reply. This is a sample message:

```
this:
  entity_id: automation.lora_direct_messages
  state: 'on'
  attributes:
    id: '1735697431879'
    last_triggered: '2025-01-01T17:47:05.651787+00:00'
    mode: parallel
    current: 0
    max: 10
    friendly_name: Lora Direct Messages
  last_changed: '2025-01-01T17:48:46.628786+00:00'
  last_reported: '2025-01-01T17:48:46.628786+00:00'
  last_updated: '2025-01-01T17:48:46.628786+00:00'
  context:
    id: 01JGHFQYN46PDY70J0SYDH2Y2H
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: device
  event:
    event_type: meshtastic_event
    data:
      device_id: cc4d04df113e51b2d8d86b05a22158ad
      type: message.received
      message: test
      entity_id: meshtastic.gateway_chdu_dm
    origin: LOCAL
    time_fired: '2025-01-01T17:49:06.516500+00:00'
    context:
      id: 01JGHFRJ2MPXM6KB0TJMV03EN7
      parent_id: null
      user_id: null
  description: event 'meshtastic_event'
```

Am I missing anything?
