### ISSUE TITLE
Add node friendly name to automation

### ISSUE THREAD

**Issue by Andrik45719** [broglep/homeassistant-meshtastic#52]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/broglep/homeassistant-meshtastic/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Can't see friendly name of node

### Describe the solution you'd like

Is it possible to add friendly node name to automation call?
Like trigger.event.data.data.from_friendly

### Describe alternatives you've considered

```
{{ (states.notify | selectattr('attributes.node_id', 'match', '12345678') | map(attribute='name')| list)[0][5:]}}
```

### Additional context

None

**Comment by broglep** [comment]
Can you share your automation to better understand the context? Are you using device trigger in combination with notify platform? If so, which device trigger are you using?
 
I think your alternative you describe is pretty viable. What definitely should be possible to add short and long name to the notify  entities as additional attribute, so you don't have to rely on the entity name itself and extract it from there. 

When it comes to adding additional data to the trigger itself, I'd like to have a more detailed look into it. It will become quite cluttered if we start adding additional data without clear concept.

**Comment by Andrik45719** [comment]
```
alias: Meshtastic2TG
description: ""
triggers:
  - trigger: event
    event_type: meshtastic_api_text_message
conditions: []
actions:
  - variables:
      node_name: >
        {{(states.notify | selectattr('attributes.node_id', 'match',
        '${trigger.event.data.data.from}') | map(attribute='name')|
        list)[0][5:]}}
    enabled: false
    - action: notify.meshualog
      metadata: {}
      data:
        message: >-
          {{node_name}} {{trigger.event.data.data.from}}: {{
          trigger.event.data.data.message }}
mode: single

```

**Comment by broglep** [comment]
Thanks, have you considered the alternative `meshtastic_message_log`? it would contain the message and from name (plus info if it was pki message)

**Comment by netscout2001** [comment]
> ```
> alias: Meshtastic2TG
> description: ""
> triggers:
>   - trigger: event
>     event_type: meshtastic_api_text_message
> conditions: []
> actions:
>   - variables:
>       node_name: >
>         {{(states.notify | selectattr('attributes.node_id', 'match',
>         '${trigger.event.data.data.from}') | map(attribute='name')|
>         list)[0][5:]}}
>     enabled: false
>     - action: notify.meshualog
>       metadata: {}
>       data:
>         message: >-
>           {{node_name}} {{trigger.event.data.data.from}}: {{
>           trigger.event.data.data.message }}
> mode: single
> ```

There is no var …data.from in my event

**Comment by agamemnen** [comment]
How did you solve the problem of displaying the node name?
The method described above did not help me.

**Comment by Andrik45719** [comment]
```
alias: Meshtastic2TG
description: ""
triggers:
  - trigger: event
    event_type: meshtastic_message_log
conditions: []
actions:
  - action: notify.meshualog
    metadata: {}
    data:
      message: "{{ trigger.event.data.from_name }}: {{trigger.event.data.message}}"
mode: single
```
